Controllers/CategoriesController.cs
using Bhosphor_Ecoshop.Data.Services;
using Bhosphor_Ecoshop.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bhosphor_Ecoshop.Controllers;

public class CategoriesController : Controller
{
    private readonly ICategoriesService _service;

    public CategoriesController(ICategoriesService service)
    {
        _service = service;
    }


    public async Task<IActionResult> Index()
    {
        var allCategories = await _service.GetAllAsync();
        return View(allCategories);
    }

    //Get: Categories/Create
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create([Bind("Name, Description")] Category category)
    {
        if (!ModelState.IsValid) return View(category);
        await _service.AddAsync(category);
        return RedirectToAction(nameof(Index));
    }

    //Get: Categories/Details/
    public async Task<IActionResult> Details(int id)
    {
        var cinemaDetails = await _service.GetByIdAsync(id);
        if (cinemaDetails == null) return View("NotFound");
        return View(cinemaDetails);
    }


    //Get: Categories/Edit/

    public async Task<IActionResult> Edit(int id)
    {
        var cinemaDetails = await _service.GetByIdAsync(id);
        if (cinemaDetails == null) return View("NotFound");
        return View(cinemaDetails);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, [Bind("Id, Name, Description")] Category category)
    {
        if (!ModelState.IsValid) return View(category);
        await _service.UpdateAsync(id, category);
        return RedirectToAction(nameof(Index));
    }


    //Get: categories/delete/1
    public async Task<IActionResult> Delete(int id)
    {
        var categoryDetails = await _service.GetByIdAsync(id);
        if (categoryDetails == null) return View("NotFound");
        return View(categoryDetails);

    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var categoryDetails = await _service.GetByIdAsync(id);
        if (categoryDetails == null) return View("NotFound");

        await _service.DeleteAsync(id);

        return RedirectToAction(nameof(Index));

    }

}

Controllers/OrdersController.cs
using Bhosphor_Ecoshop.Data.Cart;
using Bhosphor_Ecoshop.Data.Services;
using Bhosphor_Ecoshop.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Bhosphor_Ecoshop.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IProductsService _productsService;
        private readonly Wishlist _wishlist;

        public OrdersController(IProductsService productsService, Wishlist wishlist)
        {
            _productsService = productsService;
            _wishlist = wishlist;
        }

        public IActionResult Wishlist()
        {
            var items = _wishlist.GetWishlistItems();
            _wishlist.WishlistItems = items;

            var response = new WishlistVM()
            {
                Wishlist = _wishlist,
                WishlistTotal = _wishlist.GetWishlistTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToWishlist(int id)
        {
            var item = await _productsService.GetProductByIdAsync(id);

            if (item != null)
            {
                _wishlist.AddItemToWishlist(item);
            }
            return RedirectToAction(nameof(Wishlist));
        }

        public async Task<IActionResult> RemoveItemFromWishlist(int id)
        {
            var item = await _productsService.GetProductByIdAsync(id);

            if (item != null)
            {
                _wishlist.RemoveItemFromWishlist(item);
            }
            return RedirectToAction(nameof(Wishlist));
        }


    }
}

Controllers/ProductsController.cs
using Bhosphor_Ecoshop.Data;
using Bhosphor_Ecoshop.Data.Services;
using Bhosphor_Ecoshop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;


namespace Bhosphor_Ecoshop.Controllers;

public class ProductsController : Controller
{
    private readonly IProductsService _service;

    public ProductsController(IProductsService service)
    {
        _service = service;
    }

    public async Task<IActionResult> Index()
    {
        var allProducts = await _service.GetAllAsync(n => n.Category);
        return View(allProducts);
    }

    public async Task<IActionResult> Filter(string searchString)
    {
        var allProducts = await _service.GetAllAsync(n => n.Category);

        if (!string.IsNullOrEmpty(searchString))
        {
            //var filteredResult = allMovies.Where(n => n.Name.ToLower().Contains(searchString.ToLower()) || n.Description.ToLower().Contains(searchString.ToLower())).ToList();

            var filteredResultNew = allProducts.Where(n => string.Equals(n.Name, searchString, StringComparison.CurrentCultureIgnoreCase) || string.Equals(n.Description, searchString, StringComparison.CurrentCultureIgnoreCase)).ToList();

            return View("Index", filteredResultNew);
        }

        return View("Index", allProducts);
    }

    //Get : Products/Details/1
    public async Task<IActionResult> Details(int id)
    {
        var productDetails = await _service.GetProductByIdAsync(id);
        return View(productDetails); 
    }

    //GET: Products/Create
    public async Task<IActionResult> Create()
    {
        var productDropdownsData = await _service.GetNewProductDropdownsValues();

        ViewBag.Categories = new SelectList(productDropdownsData.Categories, "Id", "Name");
        ViewBag.Sellers = new SelectList(productDropdownsData.Sellers, "Id", "FirstName");
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(NewProductVM product)
    {
        if (!ModelState.IsValid)
        {
            var productDropdownsData = await _service.GetNewProductDropdownsValues();

            ViewBag.Categories = new SelectList(productDropdownsData.Categories, "Id", "Name");
            ViewBag.Sellers = new SelectList(productDropdownsData.Sellers, "Id", "FirstName");

            return View(product);
        }

        await _service.AddNewProductAsync(product);
        return RedirectToAction(nameof(Index));
    }

    //GET: Products/Edit/1
    public async Task<IActionResult> Edit(int id)
    {
        var productDetails = await _service.GetProductByIdAsync(id);
        if (productDetails == null) return View("NotFound");

        var response = new NewProductVM()
        {
            Id = productDetails.Id,
            Name = productDetails.Name,
            Description = productDetails.Description,
            Price = productDetails.Price,
            StartDate = productDetails.StartDate,
            ImageURL = productDetails.ImageURL,
            CategoryId = productDetails.CategoryId,
            SellerId = productDetails.SellerId,
        };

        var productDropdownsData = await _service.GetNewProductDropdownsValues();
        ViewBag.Categories = new SelectList(productDropdownsData.Categories, "Id", "Name");
        ViewBag.Sellers = new SelectList(productDropdownsData.Sellers, "Id", "FirstName");
        return View(response);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, NewProductVM product)
    {
        if (id != product.Id) return View("NotFound");

        if (!ModelState.IsValid)
        {
            var productDropdownsData = await _service.GetNewProductDropdownsValues();

            ViewBag.Categories = new SelectList(productDropdownsData.Categories, "Id", "Name");
            ViewBag.Sellers = new SelectList(productDropdownsData.Sellers, "Id", "FirstName");
            return View(product);
        }

        await _service.UpdateProductAsync(product);
        return RedirectToAction(nameof(Index));
    }

}

Controllers/SellersController.cs
using Microsoft.AspNetCore.Mvc;
using Bhosphor_Ecoshop.Data.Services;
using Bhosphor_Ecoshop.Models;
namespace Bhosphor_Ecoshop.Controllers;

public class SellersController : Controller
{
    private readonly ISellersService _service;

    public SellersController(ISellersService service)
    {
        _service = service;
    }

    public async Task<IActionResult> Index()
    {
        var allSellers = await _service.GetAllAsync();
        return View(allSellers);
    }

    //Get request: sellers/details/1
    public async Task<IActionResult> Details(int id)
    {
        var sellerDetails = await _service.GetByIdAsync(id);
        if (sellerDetails == null) return View("NotFound");
        return View(sellerDetails);
    }

    //GET: sellers/create

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create([Bind("ProfilePictureUrl, FirstName, LastName, Bio")] Seller seller)
    {
        if (!ModelState.IsValid) return View(seller);

        await _service.AddAsync(seller);
        return RedirectToAction(nameof(Index));
    }



    //Get: sellers/edit/1
    public async Task<IActionResult> Edit(int id)
    {
        var sellerDetails = await _service.GetByIdAsync(id);
        if (sellerDetails == null) return View("NotFound");
        return View(sellerDetails);

    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, [Bind("Id, ProfilePictureUrl, FirstName, LastName, Bio")] Seller seller)
    {
        if (!ModelState.IsValid) return View(seller);

        if (id == seller.Id)
        {
            await _service.UpdateAsync(id, seller);
            return RedirectToAction(nameof(Index));
        }
        return View(seller);

    }

    //Get: sellers/delete/1
    public async Task<IActionResult> Delete(int id)
    {
        var sellerDetails = await _service.GetByIdAsync(id);
        if (sellerDetails == null) return View("NotFound");
        return View(sellerDetails);

    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var sellerDetails = await _service.GetByIdAsync(id);
        if (sellerDetails == null) return View("NotFound");

        await _service.DeleteAsync(id);

        return RedirectToAction(nameof(Index));

    }
}

Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">You've reached the end of the internet</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Home" asp-action="Index">Home Page</a>
    </div>
</div>

Views/Shared/_CreateItem.cshtml
@model string;

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
            <i class="bi bi-plus-circle"></i> Add New
        </a>
    </div>
}

Views/Shared/_Identity.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager; 

@if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Log in
    </a>
    <span style="padding: 5px;"></span>

    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Register
    </a>
}
else
{

    @*User profile section*@
    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown"
                aria-expanded="false">
            <i class="bi bi-person-badge"></i> Hello @UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <!--asp-controller="Orders" asp-action="Index"-->
                <a class="dropdown-item">
                    <i class="bi bi-list"></i> Orders
                </a>
            </li>

            @if (User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                        <i class="bi bi-people"></i> Users
                    </a>
                </li>
            }
        </ul>
    </div>
    <span style="padding: 5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Log out
        </button>
    </form>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bhosphor_Ecoshop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bhosphor_Ecoshop.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Products" asp-action="Index">Bhosphor_Ecoshop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>

                        @if(User.Identity.IsAuthenticated)
                        {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="bi bi-gear"></i> Sections
                                    </a>

                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-controller="Sellers" asp-action="Index"><i class="bi bi-headset"></i> Seller</a>
                                        <a class="dropdown-item" asp-controller="Categories" asp-action="Index"><i class="bi bi-person-square"></i> Categories</a>
                                    </div>
                                </li>
                        }
                    
                    </ul>

                    <form class="form-inline my-2 my-lg-0" asp-controller="Products" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a product..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>

                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("WishlistSummary")
                    </ul>

                    <partial name="_Identity" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="bottom:3%;position:absolute;width:100%;">
        <div class="container" style="margin-left:0;">
            &copy; 2022 - Bhosphor_Ecoshop
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        $(document).ready(function() {
        $("#show_hide_password a").on('click', function(event) {
            event.preventDefault();
                if($('#show_hide_password input').attr("type") == "text"){
                    $('#show_hide_password input').attr('type', 'password');
                    $('#show_hide_password i').addClass( "fa-eye-slash" );
                    $('#show_hide_password i').removeClass( "fa-eye" );
                } else if($('#show_hide_password input').attr("type") == "password"){
                    $('#show_hide_password input').attr('type', 'text');
                    $('#show_hide_password i').removeClass( "fa-eye-slash" );
                    $('#show_hide_password i').addClass( "fa-eye" );
                }
            });
        });
    </script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>